// Pull the bodyweight exercise library, GIF demos and body-map geometry
// out of a local openGym checkout into this static app.
//
//   node tools/import-opengym.mjs /path/to/opengym
//
// Writes js/opengym-data.js, js/body-paths.js and media/gif/*.gif.
import fs from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';

const src = process.argv[2];
if (!src) { console.error('usage: node tools/import-opengym.mjs <opengym dir>'); process.exit(1); }
const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const lib = f => pathToFileURL(path.join(src, 'frontend/src/lib', f)).href;

const { EXDB } = await import(lib('exercises-data.js'));
const bodyPaths = (await import(lib('body-paths.js'))).default;

// Only exercises that need no equipment fit OneFit's "workout anywhere" promise
const bw = EXDB.filter(e => e.eq === 'body weight');
const out = bw.map(e => ({ id: e.id, n: e.n, bp: e.bp, tg: e.tg, sm: e.sm, st: e.st, gif: e.gif }));

fs.mkdirSync(path.join(root, 'media/gif'), { recursive: true });
let bytes = 0;
for (const e of bw) {
  const from = path.join(src, 'media/gif', e.gif);
  fs.copyFileSync(from, path.join(root, 'media/gif', e.gif));
  bytes += fs.statSync(from).size;
}

const header = '/* Generated by tools/import-opengym.mjs — do not edit by hand. */\n';
fs.writeFileSync(path.join(root, 'js/opengym-data.js'),
  header + '/* Exercise names, instructions and GIFs: hasaneyldrm/exercises-dataset, as bundled by openGym. */\n' +
  'const OGDB = ' + JSON.stringify(out) + ';\n');
fs.writeFileSync(path.join(root, 'js/body-paths.js'),
  header + '/* Body outlines: MuscleMap by Melih Colpan (MIT), as converted by openGym. */\n' +
  'const BODY_PATHS = ' + JSON.stringify(bodyPaths) + ';\n');

console.log(`${out.length} exercises, ${(bytes / 1e6).toFixed(1)} MB of GIFs`);
